# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KroSXtJ1vfB-5db5XudMrFj7ZYlrP8bC
"""

a = input("entre com o 1º valor ")
a = int(a)

b = input("entre com o 2º valor ")
b = int(b)

c = a + b

print("a soma:  ", a, "+", b, "=", c)

imput()

Entre com o 1º valor10
Entre com o 2º valor10
a soma: 10 + 10 = 20
20
'20'
imput()

#Calculadora

def soma(a, b):
  return a + b

def subtracao(a, b):
  return a - b

def multiplicacao(a, b):
  return a * b

def divisao(a, b):
  if b ! = 0 :
    return a / b
  else:
     return "Erro nao é divisao por zero!"

while True:
  print("*\n--- CALCULADORA ---")
  print("1 - Soma")
  print("2 - Subtracao")
  print("3 - Multiplicacao")
  print("4 - Divisao")
  print("5 - Sair")

  opcao = imput ("Escolha uma opcao: ")

  if opcao == "5":
    print("ENCERRADO!")
    break

  a = float(imput("Digite o 1º valor: "))
  b = float(imput)("Digite o 2º valor: "))

  if opcao == "1":
    print("Resultado:", soma(a, b))

  elif opcao == "2":
    print("Resultado", subtracao(a, b))

  elif opcao == "3":
    print("Resultado", multplicacao(a, b))

  elif opcao == "4":
    print("Resultado", divisao(a, b))

  else:
    print ("Opcao invalida! ")